package com.example.postgre.Model;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;

@Entity
@Table(uniqueConstraints = {
        @UniqueConstraint(columnNames = {"group_id", "user_id", "date", "time"})
})
//@IdClass(BudgetPK.class)
public class Budget{
    @Id
    private Long budget_id;
    private Long group_id;

    private Long user_id;
    private LocalDate date;
    private LocalTime time;
    private String title;
    private String description;
    private String amount;

//    constructor with none of attributes
    public Budget() {
    }

//    constructor with all attributes
    public Budget(Long group_id, Long user_id, LocalDate date, LocalTime time, String title, String description, String amount) {
        this.group_id = group_id;
        this.user_id = user_id;
        this.date = date;
        this.time = time;
        this.title = title;
        this.description = description;
        this.amount = amount;
    }

//    constructor without id for autogenerated ids

    public Budget(Long user_id, LocalDate date, LocalTime time, String title, String description, String amount) {
        this.user_id = user_id;
        this.date = date;
        this.time = time;
        this.title = title;
        this.description = description;
        this.amount = amount;
    }

    public long getGroup_id() {
        return group_id;
    }

    public void setGroup_id(Long group_id) {
        this.group_id = group_id;
    }

    public Long getuser_id() {
        return user_id;
    }

    public void setuser_id(Long user_id) {
        this.user_id = user_id;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public LocalTime getTime() {
        return time;
    }

    public void setTime(LocalTime time) {
        this.time = time;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }
}
